/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CadImovel;

/**
 *
 * @author user
 */
public class cadastroImovel extends javax.swing.JFrame {

    /**
     * Creates new form cadastroImovel2
     */
    public cadastroImovel() {
        initComponents();
        //teste aqui
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jtpCadastro = new javax.swing.JTabbedPane();
        jifEndereco = new javax.swing.JInternalFrame();
        jlComplemento = new javax.swing.JLabel();
        jlZona = new javax.swing.JLabel();
        jlReferencia = new javax.swing.JLabel();
        jlCondominio = new javax.swing.JLabel();
        jlUF = new javax.swing.JLabel();
        jlNumero = new javax.swing.JLabel();
        jlBairro = new javax.swing.JLabel();
        jlCidade = new javax.swing.JLabel();
        jlLogradouro = new javax.swing.JLabel();
        jtfUF = new javax.swing.JTextField();
        jtfBairro = new javax.swing.JTextField();
        jtfCidade = new javax.swing.JTextField();
        jtfLogradouro = new javax.swing.JTextField();
        jtfNumero = new javax.swing.JTextField();
        jtfCondominio = new javax.swing.JTextField();
        jtfZona = new javax.swing.JTextField();
        jtfComplemento = new javax.swing.JTextField();
        jtfReferencia = new javax.swing.JTextField();
        jbAdd = new javax.swing.JButton();
        jifDescricao = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jtfValores = new javax.swing.JInternalFrame();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jifOutros = new javax.swing.JInternalFrame();
        jLabel35 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel40 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jlCodigo = new javax.swing.JLabel();
        jcbLocacao = new javax.swing.JCheckBox();
        jtCodigo = new javax.swing.JTextField();
        jcbVenda = new javax.swing.JCheckBox();
        jcbTemporada = new javax.swing.JCheckBox();
        jcbFesta = new javax.swing.JCheckBox();
        jlTipo = new javax.swing.JLabel();
        jrbCasa = new javax.swing.JRadioButton();
        jrbApartamento = new javax.swing.JRadioButton();
        jrbSalao = new javax.swing.JRadioButton();
        jrbComercio = new javax.swing.JRadioButton();
        jrbCondominio = new javax.swing.JRadioButton();
        jlStatus = new javax.swing.JLabel();
        jtfStatus = new javax.swing.JTextField();
        jbConfirmar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jmenuCadastro = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        jifEndereco.setVisible(true);
        jifEndereco.getContentPane().setLayout(null);

        jlComplemento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlComplemento.setText("Complemento");
        jifEndereco.getContentPane().add(jlComplemento);
        jlComplemento.setBounds(530, 40, 110, 15);

        jlZona.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlZona.setText("Zona");
        jifEndereco.getContentPane().add(jlZona);
        jlZona.setBounds(540, 160, 34, 15);

        jlReferencia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlReferencia.setText("Referência");
        jifEndereco.getContentPane().add(jlReferencia);
        jlReferencia.setBounds(70, 160, 60, 15);

        jlCondominio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlCondominio.setText("Condomínio");
        jifEndereco.getContentPane().add(jlCondominio);
        jlCondominio.setBounds(68, 213, 68, 15);

        jlUF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlUF.setText("UF");
        jifEndereco.getContentPane().add(jlUF);
        jlUF.setBounds(540, 100, 16, 15);

        jlNumero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlNumero.setText("Nº");
        jifEndereco.getContentPane().add(jlNumero);
        jlNumero.setBounds(460, 40, 13, 15);

        jlBairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlBairro.setText("Bairro");
        jifEndereco.getContentPane().add(jlBairro);
        jlBairro.setBounds(312, 100, 80, 15);

        jlCidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlCidade.setText("Cidade");
        jifEndereco.getContentPane().add(jlCidade);
        jlCidade.setBounds(68, 100, 40, 15);

        jlLogradouro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlLogradouro.setText("Logradouro");
        jifEndereco.getContentPane().add(jlLogradouro);
        jlLogradouro.setBounds(68, 40, 64, 15);

        jtfUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUFActionPerformed(evt);
            }
        });
        jifEndereco.getContentPane().add(jtfUF);
        jtfUF.setBounds(540, 120, 70, 20);
        jifEndereco.getContentPane().add(jtfBairro);
        jtfBairro.setBounds(312, 120, 190, 20);
        jifEndereco.getContentPane().add(jtfCidade);
        jtfCidade.setBounds(68, 120, 150, 20);
        jifEndereco.getContentPane().add(jtfLogradouro);
        jtfLogradouro.setBounds(68, 60, 370, 20);

        jtfNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumeroActionPerformed(evt);
            }
        });
        jifEndereco.getContentPane().add(jtfNumero);
        jtfNumero.setBounds(458, 60, 50, 20);
        jifEndereco.getContentPane().add(jtfCondominio);
        jtfCondominio.setBounds(68, 234, 230, 20);
        jifEndereco.getContentPane().add(jtfZona);
        jtfZona.setBounds(538, 183, 90, 20);
        jifEndereco.getContentPane().add(jtfComplemento);
        jtfComplemento.setBounds(528, 60, 100, 20);
        jifEndereco.getContentPane().add(jtfReferencia);
        jtfReferencia.setBounds(68, 183, 450, 20);

        jbAdd.setText("Add");
        jifEndereco.getContentPane().add(jbAdd);
        jbAdd.setBounds(230, 120, 59, 23);

        jtpCadastro.addTab("Endereço", jifEndereco);

        jifDescricao.setVisible(true);
        jifDescricao.getContentPane().setLayout(null);

        jLabel1.setText("Quartos");
        jifDescricao.getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 20, 39, 14);

        jLabel2.setText("Suites");
        jifDescricao.getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 50, 60, 14);

        jLabel3.setText("Salas");
        jifDescricao.getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 80, 50, 14);

        jLabel4.setText("Lavanderia");
        jifDescricao.getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 200, 60, 14);

        jLabel23.setText("Vagas Garagem");
        jifDescricao.getContentPane().add(jLabel23);
        jLabel23.setBounds(200, 50, 75, 14);

        jLabel24.setText("Area de serviço");
        jifDescricao.getContentPane().add(jLabel24);
        jLabel24.setBounds(60, 170, 75, 14);

        jLabel25.setText("Pscina");
        jifDescricao.getContentPane().add(jLabel25);
        jLabel25.setBounds(200, 20, 30, 14);

        jLabel26.setText("Lavabos");
        jifDescricao.getContentPane().add(jLabel26);
        jLabel26.setBounds(60, 140, 40, 14);

        jLabel27.setText("Banheiros");
        jifDescricao.getContentPane().add(jLabel27);
        jLabel27.setBounds(60, 110, 47, 14);

        jLabel28.setText("Dep. Empregada");
        jifDescricao.getContentPane().add(jLabel28);
        jLabel28.setBounds(200, 80, 90, 14);

        jLabel29.setText("Pisos (Andares)");
        jifDescricao.getContentPane().add(jLabel29);
        jLabel29.setBounds(60, 230, 80, 14);

        jTextField19.setText("jTextField18");
        jifDescricao.getContentPane().add(jTextField19);
        jTextField19.setBounds(15, 80, 30, 20);

        jTextField20.setText("jTextField18");
        jifDescricao.getContentPane().add(jTextField20);
        jTextField20.setBounds(15, 110, 30, 20);

        jTextField26.setText("jTextField18");
        jifDescricao.getContentPane().add(jTextField26);
        jTextField26.setBounds(15, 200, 30, 20);

        jTextField27.setText("jTextField18");
        jifDescricao.getContentPane().add(jTextField27);
        jTextField27.setBounds(15, 50, 30, 20);

        jTextField21.setText("jTextField18");
        jifDescricao.getContentPane().add(jTextField21);
        jTextField21.setBounds(15, 20, 30, 20);

        jTextField22.setText("jTextField18");
        jifDescricao.getContentPane().add(jTextField22);
        jTextField22.setBounds(15, 140, 30, 20);

        jTextField23.setText("jTextField18");
        jifDescricao.getContentPane().add(jTextField23);
        jTextField23.setBounds(15, 170, 30, 20);

        jTextField24.setText("jTextField18");
        jifDescricao.getContentPane().add(jTextField24);
        jTextField24.setBounds(150, 20, 30, 20);

        jTextField25.setText("jTextField18");
        jifDescricao.getContentPane().add(jTextField25);
        jTextField25.setBounds(150, 80, 30, 20);

        jTextField18.setText("jTextField18");
        jifDescricao.getContentPane().add(jTextField18);
        jTextField18.setBounds(15, 230, 30, 20);

        jTextField28.setText("jTextField18");
        jifDescricao.getContentPane().add(jTextField28);
        jTextField28.setBounds(150, 50, 30, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jifDescricao.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(500, 20, 200, 50);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jifDescricao.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(500, 80, 200, 60);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jifDescricao.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(500, 150, 200, 60);

        jLabel30.setText("Tipo de imovel");
        jifDescricao.getContentPane().add(jLabel30);
        jLabel30.setBounds(400, 40, 70, 14);

        jLabel31.setText("Area Externa");
        jifDescricao.getContentPane().add(jLabel31);
        jLabel31.setBounds(410, 90, 64, 14);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jifDescricao.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(500, 220, 200, 60);

        jLabel33.setText("Acabamento");
        jifDescricao.getContentPane().add(jLabel33);
        jLabel33.setBounds(410, 180, 70, 14);

        jLabel32.setText("Outros");
        jifDescricao.getContentPane().add(jLabel32);
        jLabel32.setBounds(430, 240, 33, 14);

        jLabel14.setText("Idade Imovel");
        jifDescricao.getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 260, 63, 20);

        jTextField14.setText("jTextField14");
        jifDescricao.getContentPane().add(jTextField14);
        jTextField14.setBounds(15, 260, 30, 20);

        jtpCadastro.addTab("Descrição", jifDescricao);

        jtfValores.setVisible(true);
        jtfValores.getContentPane().setLayout(null);

        jLabel38.setText("valor locação mes");
        jtfValores.getContentPane().add(jLabel38);
        jLabel38.setBounds(10, 20, 100, 14);

        jLabel39.setText("valor  iptu");
        jtfValores.getContentPane().add(jLabel39);
        jLabel39.setBounds(10, 110, 48, 14);

        jLabel41.setText("valor condominio");
        jtfValores.getContentPane().add(jLabel41);
        jLabel41.setBounds(10, 140, 90, 14);

        jLabel43.setText("valor venda");
        jtfValores.getContentPane().add(jLabel43);
        jLabel43.setBounds(10, 50, 57, 14);

        jLabel44.setText("valor temporada");
        jtfValores.getContentPane().add(jLabel44);
        jLabel44.setBounds(10, 80, 79, 14);

        jLabel45.setText("valor diaria");
        jtfValores.getContentPane().add(jLabel45);
        jLabel45.setBounds(10, 170, 60, 14);

        jTextField33.setText("jTextField33");
        jtfValores.getContentPane().add(jTextField33);
        jTextField33.setBounds(130, 20, 65, 20);

        jTextField34.setText("jTextField34");
        jtfValores.getContentPane().add(jTextField34);
        jTextField34.setBounds(130, 50, 65, 20);

        jTextField35.setText("jTextField35");
        jtfValores.getContentPane().add(jTextField35);
        jTextField35.setBounds(130, 140, 65, 20);

        jTextField36.setText("jTextField36");
        jtfValores.getContentPane().add(jTextField36);
        jTextField36.setBounds(130, 80, 65, 20);

        jTextField37.setText("jTextField37");
        jtfValores.getContentPane().add(jTextField37);
        jTextField37.setBounds(130, 110, 65, 20);

        jTextField38.setText("jTextField38");
        jtfValores.getContentPane().add(jTextField38);
        jTextField38.setBounds(130, 170, 65, 20);

        jtpCadastro.addTab("Valores", jtfValores);

        jifOutros.setVisible(true);
        jifOutros.getContentPane().setLayout(null);

        jLabel35.setText("Medidas terreno");
        jifOutros.getContentPane().add(jLabel35);
        jLabel35.setBounds(235, 10, 90, 20);

        jTextField30.setText("jTextField30");
        jifOutros.getContentPane().add(jTextField30);
        jTextField30.setBounds(360, 10, 65, 20);

        jLabel34.setText("Area construida M");
        jifOutros.getContentPane().add(jLabel34);
        jLabel34.setBounds(235, 40, 100, 14);

        jTextField29.setText("jTextField29");
        jifOutros.getContentPane().add(jTextField29);
        jTextField29.setBounds(360, 40, 65, 20);

        jLabel36.setText("Tamanho terreno em M");
        jifOutros.getContentPane().add(jLabel36);
        jLabel36.setBounds(235, 70, 130, 14);

        jTextField31.setText("jTextField31");
        jifOutros.getContentPane().add(jTextField31);
        jTextField31.setBounds(100, 190, 110, 20);

        jLabel37.setText("Situação Escritura");
        jifOutros.getContentPane().add(jLabel37);
        jLabel37.setBounds(10, 190, 90, 14);

        jTextField32.setText("jTextField32");
        jifOutros.getContentPane().add(jTextField32);
        jTextField32.setBounds(360, 70, 65, 20);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        jifOutros.getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(570, 130, 190, 80);

        jLabel40.setText("Chaves");
        jifOutros.getContentPane().add(jLabel40);
        jLabel40.setBounds(500, 130, 36, 22);

        jLabel46.setText("observaçoes gerais");
        jifOutros.getContentPane().add(jLabel46);
        jLabel46.setBounds(460, 240, 110, 14);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jifOutros.getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(570, 20, 180, 80);

        jTextField10.setText("jTextField10");
        jifOutros.getContentPane().add(jTextField10);
        jTextField10.setBounds(100, 10, 110, 20);

        jLabel15.setText("Nº Matricula");
        jifOutros.getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 10, 58, 20);

        jLabel16.setText("Nº Conta Agua");
        jifOutros.getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 40, 90, 14);

        jTextField11.setText("jTextField11");
        jifOutros.getContentPane().add(jTextField11);
        jTextField11.setBounds(100, 130, 110, 20);

        jLabel17.setText("Nº Conta de luz");
        jifOutros.getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 70, 75, 14);

        jTextField12.setText("jTextField12");
        jifOutros.getContentPane().add(jTextField12);
        jTextField12.setBounds(100, 40, 110, 20);

        jLabel18.setText("Nº Iptu");
        jifOutros.getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 100, 80, 20);

        jTextField13.setText("jTextField13");
        jifOutros.getContentPane().add(jTextField13);
        jTextField13.setBounds(100, 100, 110, 20);

        jLabel19.setText("Cartorio");
        jifOutros.getContentPane().add(jLabel19);
        jLabel19.setBounds(10, 160, 40, 14);

        jTextField15.setText("jTextField15");
        jifOutros.getContentPane().add(jTextField15);
        jTextField15.setBounds(100, 70, 110, 20);

        jTextField17.setText("jTextField17");
        jifOutros.getContentPane().add(jTextField17);
        jTextField17.setBounds(100, 160, 110, 20);

        jLabel20.setText("Nº Contrato");
        jifOutros.getContentPane().add(jLabel20);
        jLabel20.setBounds(10, 130, 80, 14);

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane8.setViewportView(jTextArea8);

        jifOutros.getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(570, 220, 190, 80);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(2.0F);
        jSeparator1.setAlignmentY(2.0F);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jifOutros.getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 0, 220, 290);

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jifOutros.getContentPane().add(jSeparator2);
        jSeparator2.setBounds(230, 0, 220, 160);

        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jifOutros.getContentPane().add(jSeparator3);
        jSeparator3.setBounds(460, 10, 300, 100);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Mobiliada");
        jifOutros.getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(460, 20, 69, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Semi Mobiliada");
        jifOutros.getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(460, 50, 100, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Sem Mobilia");
        jifOutros.getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(460, 80, 81, 23);

        jtpCadastro.addTab("Outros", jifOutros);

        getContentPane().add(jtpCadastro);
        jtpCadastro.setBounds(160, 100, 790, 380);

        jlCodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlCodigo.setText("Código Interno");
        getContentPane().add(jlCodigo);
        jlCodigo.setBounds(40, 10, 100, 15);

        jcbLocacao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcbLocacao.setText("Locação");
        getContentPane().add(jcbLocacao);
        jcbLocacao.setBounds(40, 110, 90, 23);
        getContentPane().add(jtCodigo);
        jtCodigo.setBounds(30, 30, 110, 20);

        jcbVenda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcbVenda.setText("Venda");
        getContentPane().add(jcbVenda);
        jcbVenda.setBounds(40, 140, 90, 23);

        jcbTemporada.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcbTemporada.setText("Temporada");
        getContentPane().add(jcbTemporada);
        jcbTemporada.setBounds(40, 170, 90, 23);

        jcbFesta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcbFesta.setText("Festa");
        jcbFesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFestaActionPerformed(evt);
            }
        });
        getContentPane().add(jcbFesta);
        jcbFesta.setBounds(40, 200, 60, 23);

        jlTipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlTipo.setText("Tipo");
        getContentPane().add(jlTipo);
        jlTipo.setBounds(470, 10, 40, 15);

        buttonGroup2.add(jrbCasa);
        jrbCasa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrbCasa.setText("Casa");
        getContentPane().add(jrbCasa);
        jrbCasa.setBounds(230, 30, 55, 23);

        buttonGroup2.add(jrbApartamento);
        jrbApartamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrbApartamento.setText("Apartamento");
        getContentPane().add(jrbApartamento);
        jrbApartamento.setBounds(310, 30, 95, 23);

        buttonGroup2.add(jrbSalao);
        jrbSalao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrbSalao.setText("Salão");
        getContentPane().add(jrbSalao);
        jrbSalao.setBounds(430, 30, 57, 23);

        buttonGroup2.add(jrbComercio);
        jrbComercio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrbComercio.setText("Comércio");
        jrbComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbComercioActionPerformed(evt);
            }
        });
        getContentPane().add(jrbComercio);
        jrbComercio.setBounds(520, 30, 79, 23);

        buttonGroup2.add(jrbCondominio);
        jrbCondominio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrbCondominio.setText("Condomínio");
        getContentPane().add(jrbCondominio);
        jrbCondominio.setBounds(630, 30, 93, 23);

        jlStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlStatus.setText("Status");
        getContentPane().add(jlStatus);
        jlStatus.setBounds(880, 10, 35, 15);
        getContentPane().add(jtfStatus);
        jtfStatus.setBounds(860, 30, 90, 20);

        jbConfirmar.setText("Confirmar");
        getContentPane().add(jbConfirmar);
        jbConfirmar.setBounds(320, 500, 140, 70);

        jbCancelar.setText("Cancelar");
        getContentPane().add(jbCancelar);
        jbCancelar.setBounds(490, 500, 140, 70);

        jbEditar.setText("Editar");
        getContentPane().add(jbEditar);
        jbEditar.setBounds(660, 500, 140, 70);

        jSeparator4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(30, 100, 110, 140);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(10, 0, 980, 70);

        jMenu1.setText("File");
        jmenuCadastro.add(jMenu1);

        jMenu2.setText("Edit");
        jmenuCadastro.add(jMenu2);

        setJMenuBar(jmenuCadastro);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbFestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFestaActionPerformed

    private void jtfNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumeroActionPerformed

    private void jtfUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUFActionPerformed

    private void jrbComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbComercioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbComercioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroImovel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JCheckBox jcbFesta;
    private javax.swing.JCheckBox jcbLocacao;
    private javax.swing.JCheckBox jcbTemporada;
    private javax.swing.JCheckBox jcbVenda;
    private javax.swing.JInternalFrame jifDescricao;
    private javax.swing.JInternalFrame jifEndereco;
    private javax.swing.JInternalFrame jifOutros;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlComplemento;
    private javax.swing.JLabel jlCondominio;
    private javax.swing.JLabel jlLogradouro;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlReferencia;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLabel jlUF;
    private javax.swing.JLabel jlZona;
    private javax.swing.JMenuBar jmenuCadastro;
    private javax.swing.JRadioButton jrbApartamento;
    private javax.swing.JRadioButton jrbCasa;
    private javax.swing.JRadioButton jrbComercio;
    private javax.swing.JRadioButton jrbCondominio;
    private javax.swing.JRadioButton jrbSalao;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfCondominio;
    private javax.swing.JTextField jtfLogradouro;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfReferencia;
    private javax.swing.JTextField jtfStatus;
    private javax.swing.JTextField jtfUF;
    private javax.swing.JInternalFrame jtfValores;
    private javax.swing.JTextField jtfZona;
    private javax.swing.JTabbedPane jtpCadastro;
    // End of variables declaration//GEN-END:variables
}
