package Interface.CadImovel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Master
 */
public class cadastroImovel extends javax.swing.JFrame {

    /**
     * Creates new form cadastroImovel
     */
    public cadastroImovel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        jCheckBox1.setText("Locação");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(20, 80, 100, 23);

        jCheckBox2.setText("Venda");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(20, 110, 90, 23);

        jCheckBox3.setText("Temporada");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(20, 140, 90, 23);

        jCheckBox4.setText("Festa");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(20, 170, 60, 23);

        jLabel5.setText("Complemento");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(660, 100, 110, 14);

        jLabel6.setText("Zona");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(680, 220, 34, 14);

        jLabel7.setText("Referencia");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 220, 52, 14);

        jLabel8.setText("Condominio");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 270, 55, 14);

        jLabel9.setText("UF");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(580, 160, 13, 14);

        jLabel10.setText("Nº");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(590, 100, 12, 14);

        jLabel11.setText("Bairro");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(370, 160, 80, 14);

        jLabel12.setText("Cidade");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(200, 160, 33, 14);

        jLabel13.setText("Rua");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(200, 100, 19, 14);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(570, 180, 70, 20);

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(360, 180, 190, 20);

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(200, 180, 150, 20);

        jTextField4.setText("jTextField4");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(200, 120, 370, 20);

        jTextField5.setText("jTextField5");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(590, 120, 50, 20);

        jTextField6.setText("jTextField6");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(200, 290, 230, 20);

        jTextField7.setText("jTextField7");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(670, 240, 90, 20);

        jTextField8.setText("jTextField8");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(660, 120, 100, 20);

        jTextField9.setText("jTextField9");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(200, 240, 450, 20);

        jLabel14.setText("Idade Imovel");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(700, 320, 63, 20);

        jLabel15.setText("Nº Matricula");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(200, 330, 58, 20);

        jLabel16.setText("Nº Conta Agua");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(300, 330, 90, 14);

        jLabel17.setText("Nº Conta de luz");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(410, 330, 75, 14);

        jLabel18.setText("Nº Iptu");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(510, 330, 80, 14);

        jLabel19.setText("Cartorio");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(610, 330, 40, 14);

        jTextField10.setText("jTextField10");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(200, 350, 80, 20);

        jTextField11.setText("jTextField11");
        getContentPane().add(jTextField11);
        jTextField11.setBounds(300, 350, 90, 20);

        jTextField12.setText("jTextField12");
        getContentPane().add(jTextField12);
        jTextField12.setBounds(410, 350, 80, 20);

        jTextField13.setText("jTextField13");
        getContentPane().add(jTextField13);
        jTextField13.setBounds(510, 350, 80, 20);

        jTextField14.setText("jTextField14");
        getContentPane().add(jTextField14);
        jTextField14.setBounds(710, 350, 30, 20);

        jTextField15.setText("jTextField15");
        getContentPane().add(jTextField15);
        jTextField15.setBounds(600, 350, 100, 20);

        jTextField16.setText("jTextField16");
        getContentPane().add(jTextField16);
        jTextField16.setBounds(20, 40, 110, 20);

        jLabel21.setText("Codigo Interno");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(20, 20, 72, 14);

        jLabel20.setText("Nº Contrato");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(200, 380, 80, 14);

        jTextField17.setText("jTextField17");
        getContentPane().add(jTextField17);
        jTextField17.setBounds(200, 400, 170, 20);

        jCheckBox5.setText("Casa");
        getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(300, 40, 49, 23);

        jCheckBox6.setText("Condominio");
        getContentPane().add(jCheckBox6);
        jCheckBox6.setBounds(380, 40, 81, 23);

        jCheckBox7.setText("Apartamento");
        getContentPane().add(jCheckBox7);
        jCheckBox7.setBounds(480, 40, 90, 23);

        jCheckBox8.setText("Salão");
        getContentPane().add(jCheckBox8);
        jCheckBox8.setBounds(580, 40, 51, 23);

        jCheckBox9.setText("Ponto Comercial");
        getContentPane().add(jCheckBox9);
        jCheckBox9.setBounds(640, 40, 110, 23);

        jLabel22.setText("Tipo");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(240, 40, 40, 14);

        jLabel1.setText("Quartos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 440, 39, 14);

        jLabel2.setText("Suites");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 470, 60, 14);

        jLabel3.setText("Salas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 510, 50, 14);

        jLabel4.setText("Lavanderia");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 550, 60, 14);

        jLabel23.setText("Vagas Garagem");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(360, 480, 75, 14);

        jLabel24.setText("Area de serviço");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(210, 490, 75, 14);

        jLabel25.setText("Pscina");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(530, 440, 30, 14);

        jLabel26.setText("Lavabos");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(210, 440, 40, 14);

        jLabel27.setText("Banheiros");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(70, 550, 47, 14);

        jLabel28.setText("Dep. Empregada");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(520, 480, 90, 14);

        jLabel29.setText("Pisos (Andares)");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(360, 440, 80, 14);

        jTextField19.setText("jTextField18");
        getContentPane().add(jTextField19);
        jTextField19.setBounds(30, 510, 30, 20);

        jTextField20.setText("jTextField18");
        getContentPane().add(jTextField20);
        jTextField20.setBounds(30, 550, 30, 20);

        jTextField26.setText("jTextField18");
        getContentPane().add(jTextField26);
        jTextField26.setBounds(150, 550, 30, 20);

        jTextField27.setText("jTextField18");
        getContentPane().add(jTextField27);
        jTextField27.setBounds(30, 470, 30, 20);

        jTextField21.setText("jTextField18");
        getContentPane().add(jTextField21);
        jTextField21.setBounds(30, 440, 30, 20);

        jTextField22.setText("jTextField18");
        getContentPane().add(jTextField22);
        jTextField22.setBounds(150, 450, 30, 20);

        jTextField23.setText("jTextField18");
        getContentPane().add(jTextField23);
        jTextField23.setBounds(150, 490, 30, 20);

        jTextField24.setText("jTextField18");
        getContentPane().add(jTextField24);
        jTextField24.setBounds(460, 440, 30, 20);

        jTextField25.setText("jTextField18");
        getContentPane().add(jTextField25);
        jTextField25.setBounds(460, 480, 30, 20);

        jTextField18.setText("jTextField18");
        getContentPane().add(jTextField18);
        jTextField18.setBounds(310, 440, 30, 20);

        jTextField28.setText("jTextField18");
        getContentPane().add(jTextField28);
        jTextField28.setBounds(310, 480, 30, 20);

        jCheckBox10.setText("Mobiliado");
        getContentPane().add(jCheckBox10);
        jCheckBox10.setBounds(20, 600, 69, 23);

        jCheckBox11.setText("Semi-Mobiliado");
        getContentPane().add(jCheckBox11);
        jCheckBox11.setBounds(20, 630, 100, 23);

        jCheckBox12.setText("Sem mobilia");
        getContentPane().add(jCheckBox12);
        jCheckBox12.setBounds(20, 650, 81, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(720, 420, 210, 60);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(720, 490, 210, 60);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(720, 570, 210, 60);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(720, 640, 210, 60);

        jLabel30.setText("Tipo de imovel");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(640, 450, 70, 14);

        jLabel31.setText("Area Externa");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(630, 520, 64, 14);

        jLabel32.setText("Outros");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(660, 670, 33, 14);

        jLabel33.setText("Acabamento");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(640, 600, 70, 14);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(120, 610, 166, 60);

        jLabel34.setText("Area construida M");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(250, 750, 100, 14);

        jLabel35.setText("Medidas terreno");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(390, 750, 90, 14);

        jLabel36.setText("Tamanho terreno em M");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(500, 750, 130, 14);

        jLabel37.setText("Situação Escritura");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(660, 750, 90, 14);

        jTextField29.setText("jTextField29");
        getContentPane().add(jTextField29);
        jTextField29.setBounds(250, 780, 65, 20);

        jTextField30.setText("jTextField30");
        getContentPane().add(jTextField30);
        jTextField30.setBounds(390, 790, 65, 20);

        jTextField31.setText("jTextField31");
        getContentPane().add(jTextField31);
        jTextField31.setBounds(500, 790, 65, 20);

        jTextField32.setText("jTextField32");
        getContentPane().add(jTextField32);
        jTextField32.setBounds(660, 790, 65, 20);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroImovel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
