/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CadImovel;

import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import validacao.validacao;

/**
 *
 * @author user
 */
public class cadastroImovelHome extends javax.swing.JFrame {

    int user;

    /**
     * Creates new form cadastroImovelHome
     */
    public cadastroImovelHome() {
        initComponents();
        fechar();

    }

    public cadastroImovelHome(int user) {
                 this.user = user;

        initComponents();
        fechar();
        if (user <= 2) {
            jbRemover.setEnabled(true);
            jbCadastrar.setEnabled(true);
        } else {
            jbRemover.setEnabled(false);
            jbCadastrar.setEnabled(false);
        }

    }

    public void fechar() {
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {

                String ObjButtons[] = {"Sim", "Não"};
                int PromptResult = JOptionPane.showOptionDialog(null, "Esta certo que quer Fechar ?", "Verificação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, ObjButtons, ObjButtons[0]);
                if (PromptResult == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbCadastrar = new javax.swing.JButton();
        jbVisualisar = new javax.swing.JButton();
        jbRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcbCasa = new javax.swing.JCheckBox();
        jcbApartamento = new javax.swing.JCheckBox();
        jcbSalao = new javax.swing.JCheckBox();
        jcbTemporario = new javax.swing.JCheckBox();
        jcbComercio = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jbPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtNomeProprietario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtBairro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtRua = new javax.swing.JTextField();
        jtQtdQuarto = new javax.swing.JTextField();
        jtVagasGaragem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jcbEstado = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jtCidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmLogin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.setEnabled(false);
        jbCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCadastrarMouseClicked(evt);
            }
        });
        getContentPane().add(jbCadastrar);
        jbCadastrar.setBounds(110, 250, 199, 87);

        jbVisualisar.setText("Visualizar");
        jbVisualisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbVisualisarMouseClicked(evt);
            }
        });
        getContentPane().add(jbVisualisar);
        jbVisualisar.setBounds(400, 250, 195, 88);

        jbRemover.setText("Remover");
        jbRemover.setEnabled(false);
        jbRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRemoverMouseClicked(evt);
            }
        });
        getContentPane().add(jbRemover);
        jbRemover.setBounds(690, 250, 199, 94);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 970, 200);

        jcbCasa.setText("casa");
        getContentPane().add(jcbCasa);
        jcbCasa.setBounds(270, 380, 60, 30);

        jcbApartamento.setText("apartamento");
        getContentPane().add(jcbApartamento);
        jcbApartamento.setBounds(350, 380, 100, 30);

        jcbSalao.setText("Salão");
        getContentPane().add(jcbSalao);
        jcbSalao.setBounds(470, 380, 60, 30);

        jcbTemporario.setText("Temporario");
        getContentPane().add(jcbTemporario);
        jcbTemporario.setBounds(560, 380, 100, 30);

        jcbComercio.setText("Comercio");
        getContentPane().add(jcbComercio);
        jcbComercio.setBounds(680, 380, 80, 30);

        jLabel1.setText("Filtros");
        jLabel1.setMinimumSize(new java.awt.Dimension(35, 18));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 380, 40, 20);

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPesquisarMouseEntered(evt);
            }
        });
        getContentPane().add(jbPesquisar);
        jbPesquisar.setBounds(800, 430, 199, 91);

        jLabel2.setText("Nome do Proprietario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 420, 140, 14);
        getContentPane().add(jtNomeProprietario);
        jtNomeProprietario.setBounds(30, 440, 290, 20);

        jLabel3.setText("Bairro");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 480, 60, 14);
        getContentPane().add(jtBairro);
        jtBairro.setBounds(360, 500, 140, 20);

        jLabel4.setText("Estado");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(710, 480, 60, 14);
        getContentPane().add(jtRua);
        jtRua.setBounds(30, 500, 300, 20);
        getContentPane().add(jtQtdQuarto);
        jtQtdQuarto.setBounds(380, 440, 30, 20);
        getContentPane().add(jtVagasGaragem);
        jtVagasGaragem.setBounds(480, 440, 30, 20);

        jLabel5.setText("Rua");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 480, 40, 14);

        jLabel6.setText("Qtd de quarto");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 420, 80, 14);

        jLabel7.setText("Vagas de Garagem");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 420, 140, 14);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(-10, 550, 1040, 10);

        jcbEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbEstado);
        jcbEstado.setBounds(700, 500, 66, 23);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(180, 410, 580, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 360, 1030, 10);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(180, 360, 10, 50);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(760, 360, 10, 50);
        getContentPane().add(jtCidade);
        jtCidade.setBounds(540, 500, 140, 20);

        jLabel8.setText("Cidade");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(570, 480, 33, 14);

        jMenu1.setText("File");

        jmLogin.setText("Login");
        jmLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmLoginMousePressed(evt);
            }
        });
        jMenu1.add(jmLogin);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastrarMouseClicked
        if (jbCadastrar.isEnabled()) {
            new cadastroImovel(user).setVisible(true);     // TODO add your handling code here:
            dispose();
        }


    }//GEN-LAST:event_jbCadastrarMouseClicked

    private void jbRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemoverMouseClicked

        if (jbRemover.isEnabled()) {

        }
// TODO add your handling code here:
    }//GEN-LAST:event_jbRemoverMouseClicked

    private void jmLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmLoginMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmLoginMousePressed

    private void jbVisualisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVisualisarMouseClicked
        //Falta pegar a id da table;
        String idImovel = "vazio no momento";
        new cadastroImovel(idImovel, user).setVisible(true);
        dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jbVisualisarMouseClicked

    private void jbPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPesquisarMouseEntered

// TODO add your handling code here:
    }//GEN-LAST:event_jbPesquisarMouseEntered

    private void jbPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPesquisarMouseClicked
        // Verificar campos antes de pesquisar 
        boolean control = true;
        // Falta Querry
        
        if(jcbCasa.isSelected()) {
     
        }
          
        if(jcbApartamento.isSelected()) {
     
        }
          
        if(jcbSalao.isSelected()) {
     
        }
          
        if(jcbTemporario.isSelected()) {
     
        }
          
        if(jcbComercio.isSelected()) {
     
        }
        

        if (jtNomeProprietario.getText().equals("")) {
            jtNomeProprietario.setBackground(Color.white);
        } else if (!jtNomeProprietario.getText().equals("") && validacao.validaLetras(jtNomeProprietario.getText())) {
            jtNomeProprietario.setBackground(Color.white);
        } else {
            jtNomeProprietario.setBackground(Color.red);
            control = false;
        }

        if (jtQtdQuarto.getText().equals("")) {
            jtQtdQuarto.setBackground(Color.white);
        } else if (!jtQtdQuarto.getText().equals("") && validacao.validaNumeros(jtQtdQuarto.getText())) {

            jtQtdQuarto.setBackground(Color.white);
        } else {
            jtQtdQuarto.setBackground(Color.red);
            control = false;
        }

        if (jtVagasGaragem.getText().equals("")) {
            jtVagasGaragem.setBackground(Color.white);
        } else if (!jtVagasGaragem.getText().equals("") && validacao.validaNumeros(jtVagasGaragem.getText())) {

            jtVagasGaragem.setBackground(Color.white);
        } else {
            jtVagasGaragem.setBackground(Color.red);
            control = false;
        }

        if (jtRua.getText().equals("")) {
            jtRua.setBackground(Color.white);
        } else if (!jtRua.getText().equals("") && validacao.validaLetras(jtRua.getText())) {
            jtRua.setBackground(Color.white);
        } else {
            jtRua.setBackground(Color.red);
            control = false;
        }
        if (jtBairro.getText().equals("")) {
            jtBairro.setBackground(Color.white);
        } else if (!jtBairro.getText().equals("") && validacao.validaLetras(jtBairro.getText())) {

            jtBairro.setBackground(Color.white);
        } else {
            jtBairro.setBackground(Color.red);
            control = false;
        }
        if (jtCidade.getText().equals("")) {

        } else if (!jtCidade.getText().equals("") && validacao.validaLetras(jtCidade.getText())) {

            jtCidade.setBackground(Color.white);
        } else {
            jtCidade.setBackground(Color.red);
            control = false;
        }

        // Mandar Estado na querry
        // inserir pesquisa no banco // falta coisas..
        if (control) {

        } else {

            control = true;
        }

        // fim verificação   // TODO add your handling code here:
    }//GEN-LAST:event_jbPesquisarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroImovelHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroImovelHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroImovelHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroImovelHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroImovelHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbRemover;
    private javax.swing.JButton jbVisualisar;
    private javax.swing.JCheckBox jcbApartamento;
    private javax.swing.JCheckBox jcbCasa;
    private javax.swing.JCheckBox jcbComercio;
    private javax.swing.JComboBox jcbEstado;
    private javax.swing.JCheckBox jcbSalao;
    private javax.swing.JCheckBox jcbTemporario;
    private javax.swing.JMenuItem jmLogin;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JTextField jtNomeProprietario;
    private javax.swing.JTextField jtQtdQuarto;
    private javax.swing.JTextField jtRua;
    private javax.swing.JTextField jtVagasGaragem;
    // End of variables declaration//GEN-END:variables
}
