/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TelaPrincipal;

import dao.LoginDAO;
import global.model.MD5;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.pessoa.Login;

/**
 *
 * @author Sala
 */
public class TelaLogin extends javax.swing.JDialog {

    private static TelaLogin instancia;
    private String usuario;

    public TelaLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fecharLogin();

    }

    public TelaLogin() {
    }

    public static TelaLogin getInstancia() {
        if (instancia == null) {
            instancia = new TelaLogin();
        }
        return instancia;
    }

    public static void encerrarInstancia() {
        instancia = null;
    }

    public void fecharLogin() {
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                System.exit(0);
            }
        });

    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public void limpaCampos() {
        jtfUsuario.setText("");
        jpfSenha.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlImagem = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jbAcessar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jlTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(704, 460));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlImagem.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jlImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/corretagem_imob3.png"))); // NOI18N
        getContentPane().add(jlImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 200, 340));

        jlUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jlUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/usuario.png"))); // NOI18N
        jlUsuario.setText("Usuário:");
        getContentPane().add(jlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 150, 40));

        jlSenha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jlSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/password3.png"))); // NOI18N
        jlSenha.setText("  Senha:");
        getContentPane().add(jlSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 150, 40));

        jtfUsuario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfUsuario.setText("teste");
        getContentPane().add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 190, 40));

        jpfSenha.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jpfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jpfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 190, 40));

        jbAcessar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ok.png"))); // NOI18N
        jbAcessar.setText("<html><center>Acessar<br/></html>");
        jbAcessar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbAcessarMousePressed(evt);
            }
        });
        jbAcessar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAcessarKeyPressed(evt);
            }
        });
        getContentPane().add(jbAcessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 140, 70));

        jbCancelar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel.png"))); // NOI18N
        jbCancelar.setText("<html><center>Cancelar<br/></html>");
        jbCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbCancelarMousePressed(evt);
            }
        });
        getContentPane().add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 140, 70));

        jlTitulo.setFont(new java.awt.Font("Arial", 0, 44)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Sistema de Cadastro de Imóveis");
        getContentPane().add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelarMousePressed
        System.exit(0);
    }//GEN-LAST:event_jbCancelarMousePressed

    private void jbAcessarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAcessarMousePressed
        try {
            verificaLogin();
        } catch (Exception ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jbAcessarMousePressed

    private void jbAcessarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAcessarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                verificaLogin();
            } catch (Exception ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
    }//GEN-LAST:event_jbAcessarKeyPressed

    private void jpfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                verificaLogin();
            } catch (Exception ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
    }//GEN-LAST:event_jpfSenhaKeyPressed

    public boolean verificaLogin() throws Exception {
        MD5 md5 = new MD5();
        Sessao sessao = Sessao.getInstance();
        LoginDAO loginDAO = new LoginDAO();
        List<Login> logins = new ArrayList<Login>();
        logins = loginDAO.getAll();

        for (int i = 0; i < logins.size(); i++) {
            if (jtfUsuario.getText().equals(logins.get(i).getNomeUsuario()) && md5.gerarMD5(jpfSenha.getText()).equals(logins.get(i).getSenhaUsuario())) {
                setUsuario(logins.get(i).getNomeUsuario());
                sessao.setUsuario(logins.get(i));
                return true;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaLogin telaLogin = new TelaLogin(new javax.swing.JFrame(), true);
                telaLogin.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                telaLogin.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAcessar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JLabel jlImagem;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
