/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Relatorio;

/**
 *
 * @author jeanbrock
 */
public class RelatorioHome extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioHome
     */
    public RelatorioHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgRelatotio = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jbSalvarRelatorio = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbImprimirRelatorio = new javax.swing.JButton();
        jlTipoRelatório = new javax.swing.JLabel();
        jsRelatorio = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 640));
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setPreferredSize(new java.awt.Dimension(1024, 640));
        getContentPane().setLayout(null);

        btgRelatotio.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButton1.setText("Imóveis Ativos");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(50, 100, 160, 30);

        btgRelatotio.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButton2.setText("jRadioButton2");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(50, 140, 160, 30);

        btgRelatotio.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButton3.setText("jRadioButton3");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(50, 180, 160, 30);

        btgRelatotio.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButton4.setText("jRadioButton4");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(50, 220, 160, 30);

        btgRelatotio.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButton5.setText("jRadioButton5");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(50, 260, 160, 30);

        jbSalvarRelatorio.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jbSalvarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pdf.png"))); // NOI18N
        jbSalvarRelatorio.setText("<html><center>Salvar<br/>Relatório</html>");
        getContentPane().add(jbSalvarRelatorio);
        jbSalvarRelatorio.setBounds(600, 170, 140, 70);

        jbCancelar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        getContentPane().add(jbCancelar);
        jbCancelar.setBounds(600, 250, 140, 70);

        jbImprimirRelatorio.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jbImprimirRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/imprimir.png"))); // NOI18N
        jbImprimirRelatorio.setText("<html><center>Imprimir<br/>Relatório</html>");
        getContentPane().add(jbImprimirRelatorio);
        jbImprimirRelatorio.setBounds(600, 90, 140, 70);

        jlTipoRelatório.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlTipoRelatório.setText("Selecionar Tipo de Relatório");
        getContentPane().add(jlTipoRelatório);
        jlTipoRelatório.setBounds(40, 50, 210, 30);

        jsRelatorio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerar Relatório", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N
        getContentPane().add(jsRelatorio);
        jsRelatorio.setBounds(20, 20, 740, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgRelatotio;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbImprimirRelatorio;
    private javax.swing.JButton jbSalvarRelatorio;
    private javax.swing.JLabel jlTipoRelatório;
    private javax.swing.JSeparator jsRelatorio;
    // End of variables declaration//GEN-END:variables
}
