/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Locacao;

/**
 *
 * @author user
 */
public class CadLocacao extends javax.swing.JFrame {

    /**
     * Creates new form CadLocacao
     */
    public CadLocacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbRemover = new javax.swing.JButton();
        jbRemover1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jbRemover2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jbRemover3 = new javax.swing.JButton();
        jbRemover4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 50, 454, 110);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(130, 330, 454, 110);

        jLabel1.setText("Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 110, 33, 14);

        jLabel2.setText("Imovel");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 420, 32, 14);

        jbRemover.setText("Efetuar Locação");
        jbRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRemoverMouseClicked(evt);
            }
        });
        getContentPane().add(jbRemover);
        jbRemover.setBounds(850, 210, 150, 30);

        jbRemover1.setText("Pesquisar");
        jbRemover1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRemover1MouseClicked(evt);
            }
        });
        getContentPane().add(jbRemover1);
        jbRemover1.setBounds(730, 520, 199, 30);

        jTextField1.setText("Id Imovel , Endereço e Nome  Proprietario");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 230, 450, 30);

        jTextField2.setText("Id Cliente, Nome ");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 190, 450, 30);

        jbRemover2.setText("Selecionar Imovel");
        jbRemover2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRemover2MouseClicked(evt);
            }
        });
        getContentPane().add(jbRemover2);
        jbRemover2.setBounds(650, 360, 199, 50);

        jLabel3.setText("Id cliente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 90, 14);

        jLabel4.setText("Nome Cliente");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 20, 80, 14);

        jTextField8.setText("jTextField8");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(90, 20, 100, 20);

        jTextField9.setText("jTextField9");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(300, 20, 310, 20);

        jbRemover3.setText("Pesquisar");
        jbRemover3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRemover3MouseClicked(evt);
            }
        });
        jbRemover3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemover3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbRemover3);
        jbRemover3.setBounds(630, 20, 199, 30);

        jbRemover4.setText("Selecionar Cliente");
        jbRemover4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRemover4MouseClicked(evt);
            }
        });
        getContentPane().add(jbRemover4);
        jbRemover4.setBounds(650, 90, 199, 50);

        jLabel12.setText("IdImovel");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 480, 70, 30);

        jLabel13.setText("Nome Proprietario");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(200, 480, 110, 14);

        jLabel14.setText("Rua");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 530, 19, 20);

        jLabel15.setText("Bairro");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(400, 530, 28, 14);

        jLabel16.setText("Estado");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(530, 530, 33, 14);

        jLabel5.setText("Data do inicio do contrato");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(600, 240, 140, 14);

        jLabel6.setText("Data do fim do contrato");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(770, 240, 150, 20);

        jLabel7.setText("Cliente selecionado");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 190, 92, 14);

        jLabel8.setText("Imovel Selecionado");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 240, 100, 14);

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(620, 270, 59, 20);

        jTextField4.setText("jTextField4");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(780, 270, 59, 20);

        jTextField5.setText("jTextField5");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(110, 480, 59, 20);

        jTextField6.setText("jTextField6");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(310, 480, 300, 20);

        jTextField7.setText("jTextField7");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(80, 530, 280, 20);

        jTextField10.setText("jTextField10");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(440, 530, 65, 20);

        jTextField11.setText("jTextField11");
        getContentPane().add(jTextField11);
        jTextField11.setBounds(580, 530, 65, 20);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemoverMouseClicked

        if (jbRemover.isEnabled()) {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRemoverMouseClicked

    private void jbRemover1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemover1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRemover1MouseClicked

    private void jbRemover2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemover2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRemover2MouseClicked

    private void jbRemover3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemover3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRemover3MouseClicked

    private void jbRemover4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemover4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRemover4MouseClicked

    private void jbRemover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemover3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRemover3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton jbRemover;
    private javax.swing.JButton jbRemover1;
    private javax.swing.JButton jbRemover2;
    private javax.swing.JButton jbRemover3;
    private javax.swing.JButton jbRemover4;
    // End of variables declaration//GEN-END:variables
}
