/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Locacao;

/**
 *
 * @author user
 */
public class CadLocacao extends javax.swing.JFrame {

    /**
     * Creates new form CadLocacao
     */
    public CadLocacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jbRemover1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jbRemover2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jbRemover3 = new javax.swing.JButton();
        jbRemover4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtDataInicio = new javax.swing.JTextField();
        jtDataFim = new javax.swing.JTextField();
        jtIdImovel = new javax.swing.JTextField();
        jtNomeProprietario = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jcbEstado = new javax.swing.JComboBox();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jtCidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jbRemover5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(32, 80, 810, 110);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 360, 810, 110);

        jLabel1.setText("Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 60, 33, 14);

        jLabel2.setText("Imovel");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 340, 32, 14);

        jbCancelar.setText("Cancelar");
        jbCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(jbCancelar);
        jbCancelar.setBounds(860, 260, 150, 40);

        jbRemover1.setText("Pesquisar");
        jbRemover1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRemover1MouseClicked(evt);
            }
        });
        getContentPane().add(jbRemover1);
        jbRemover1.setBounds(860, 530, 150, 40);

        jTextField1.setText("Id Imovel , Endereço e Nome  Proprietario");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(50, 280, 450, 30);

        jTextField2.setText("Id Cliente, Nome ");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(50, 220, 450, 30);

        jbRemover2.setText("Selecionar Imovel");
        jbRemover2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRemover2MouseClicked(evt);
            }
        });
        getContentPane().add(jbRemover2);
        jbRemover2.setBounds(860, 390, 150, 40);

        jLabel3.setText("Id cliente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 10, 90, 20);

        jLabel4.setText("Nome Cliente");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 10, 80, 20);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(70, 30, 100, 20);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(190, 30, 310, 20);

        jbRemover3.setText("Pesquisar");
        jbRemover3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRemover3MouseClicked(evt);
            }
        });
        jbRemover3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemover3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbRemover3);
        jbRemover3.setBounds(860, 10, 150, 40);

        jbRemover4.setText("Selecionar Cliente");
        jbRemover4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRemover4MouseClicked(evt);
            }
        });
        getContentPane().add(jbRemover4);
        jbRemover4.setBounds(860, 100, 150, 40);

        jLabel12.setText("IdImovel");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 470, 70, 30);

        jLabel13.setText("Nome Proprietario");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(190, 480, 110, 14);

        jLabel14.setText("Rua");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(70, 520, 19, 20);

        jLabel15.setText("Bairro");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(390, 520, 28, 14);

        jLabel16.setText("Estado");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(730, 520, 33, 14);

        jLabel5.setText("Inicio do Contrato");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(560, 270, 140, 20);

        jLabel6.setText("Fim do Contrato");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(680, 270, 150, 20);

        jLabel7.setText("Cliente selecionado");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 200, 92, 14);

        jLabel8.setText("Imovel Selecionado");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 260, 100, 14);
        getContentPane().add(jtDataInicio);
        jtDataInicio.setBounds(560, 290, 80, 20);
        getContentPane().add(jtDataFim);
        jtDataFim.setBounds(680, 290, 80, 20);
        getContentPane().add(jtIdImovel);
        jtIdImovel.setBounds(70, 500, 80, 20);
        getContentPane().add(jtNomeProprietario);
        jtNomeProprietario.setBounds(190, 500, 300, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(70, 540, 280, 20);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(390, 540, 120, 20);

        jcbEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbEstado);
        jcbEstado.setBounds(730, 540, 66, 23);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 320, 1030, 10);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(0, 190, 1030, 10);

        jtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jtCidade);
        jtCidade.setBounds(550, 540, 140, 20);
        jtCidade.getAccessibleContext().setAccessibleName("");

        jLabel9.setText("Cidade");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(550, 520, 33, 14);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(0, 470, 1030, 10);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(0, 60, 1030, 10);

        jbRemover5.setText("Efetuar Locação");
        jbRemover5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRemover5MouseClicked(evt);
            }
        });
        getContentPane().add(jbRemover5);
        jbRemover5.setBounds(860, 210, 150, 40);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelarMouseClicked

        if (jbCancelar.isEnabled()) {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarMouseClicked

    private void jbRemover1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemover1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRemover1MouseClicked

    private void jbRemover2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemover2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRemover2MouseClicked

    private void jbRemover3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemover3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRemover3MouseClicked

    private void jbRemover4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemover4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRemover4MouseClicked

    private void jbRemover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemover3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRemover3ActionPerformed

    private void jtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCidadeActionPerformed

    private void jbRemover5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemover5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRemover5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbRemover1;
    private javax.swing.JButton jbRemover2;
    private javax.swing.JButton jbRemover3;
    private javax.swing.JButton jbRemover4;
    private javax.swing.JButton jbRemover5;
    private javax.swing.JComboBox jcbEstado;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JTextField jtDataFim;
    private javax.swing.JTextField jtDataInicio;
    private javax.swing.JTextField jtIdImovel;
    private javax.swing.JTextField jtNomeProprietario;
    // End of variables declaration//GEN-END:variables
}
