/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Locacao;

/**
 *
 * @author user
 */
public class CadLocacaoHome extends javax.swing.JFrame {

    /**
     * Creates new form CadLocacaoHome
     */
    public CadLocacaoHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtCep = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jtCidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 640));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 30, 910, 210);

        jButton1.setText("visualizar");
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 250, 195, 88);

        jButton2.setText("Cadastro de locação");
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 250, 195, 88);

        jButton3.setText("Pesquisar");
        getContentPane().add(jButton3);
        jButton3.setBounds(800, 410, 195, 88);

        jLabel1.setText("Nome do Inquilino");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 440, 200, 14);

        jLabel2.setText("Nome do Proprietario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 380, 140, 14);

        jLabel3.setText("idImovel");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 380, 80, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 460, 350, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 400, 350, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(30, 400, 90, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(20, 540, 260, 20);

        jLabel4.setText("Rua");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 520, 34, 20);

        jLabel5.setText("bairro");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 520, 28, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(310, 540, 160, 20);

        jLabel6.setText("estado");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(690, 520, 33, 20);
        getContentPane().add(jtCep);
        jtCep.setBounds(580, 400, 90, 20);

        jLabel7.setText("Cep do imóvel");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(580, 380, 100, 14);

        jcbEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbEstado);
        jcbEstado.setBounds(690, 540, 66, 23);

        jButton4.setText("controle de locação");
        getContentPane().add(jButton4);
        jButton4.setBounds(640, 250, 195, 88);
        getContentPane().add(jtCidade);
        jtCidade.setBounds(490, 540, 160, 20);

        jLabel8.setText("Cidade");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(500, 520, 50, 20);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(0, 350, 1030, 10);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadLocacaoHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadLocacaoHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadLocacaoHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadLocacaoHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadLocacaoHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JComboBox jcbEstado;
    private javax.swing.JTextField jtCep;
    private javax.swing.JTextField jtCidade;
    // End of variables declaration//GEN-END:variables
}
