/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CadCliente;

import Interface.TelaPrincipal.Sessao;
import dao.PessoaDAO;
import dao.PessoaFisicaDAO;
import dao.PessoaJuridicaDAO;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import model.TableModel.PessoaFisicaTableModel;
import model.TableModel.PessoaJuridicaTableModel;
import model.TableModel.PessoaTableModel;
import model.pessoa.Pessoa;
import model.pessoa.PessoaFisica;
import model.pessoa.PessoaJuridica;

/**
 *
 * @author Sala
 */
public class cadastroClienteHome extends javax.swing.JFrame {

    private static cadastroClienteHome instancia;
    int user;

    /**
     * Creates new form cadastroClienteHome
     */
    public cadastroClienteHome() {
        this.setUndecorated(true);
        initComponents();
        setAlwaysOnTop(true);
        this.setTitle("Consulta de Clientes");
        jcbPessoaFisica.setSelected(true);
        jcbPessoaJuridica.setSelected(true);
        popularTabela();
        mascaraTelefone();
        acesso(Sessao.getInstance().getUsuario().getNivelAcesso());
    }

    public static cadastroClienteHome getInstancia() {
        if (instancia == null) {
            instancia = new cadastroClienteHome();
        }
        return instancia;
    }

    public static void encerrarInstancia() {
        instancia = null;
    }

    public void acesso(int nivel) {
        DisableEnable(false);
        switch (nivel) {
            case 1:
                DisableEnable(true);
                jbCadastrar.setEnabled(true);
                jbVisualizar.setEnabled(true);
                jbRemover.setEnabled(true);
                jbPesquisar.setEnabled(true);
                break;
            case 2:
                DisableEnable(true);
                jbCadastrar.setEnabled(true);
                jbVisualizar.setEnabled(true);
                jbRemover.setEnabled(true);
                jbPesquisar.setEnabled(true);
                break;
            case 3:
                DisableEnable(false);
                jbPesquisar.setEnabled(true);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Acesso negado!\nNível de Acesso Inválido");
        }
    }

    public void DisableEnable(Boolean b) {
        jbCadastrar.setEnabled(b);
        jbVisualizar.setEnabled(b);
        jbRemover.setEnabled(b);
        jbPesquisar.setEnabled(b);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();
        jbCadastrar = new javax.swing.JButton();
        jbVisualizar = new javax.swing.JButton();
        jbRemover = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();
        jlFiltros = new javax.swing.JLabel();
        jcbPessoaFisica = new javax.swing.JCheckBox();
        jcbPessoaJuridica = new javax.swing.JCheckBox();
        jtNome = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jftTelefone = new javax.swing.JFormattedTextField();
        jlCPF = new javax.swing.JLabel();
        jftCPF = new javax.swing.JFormattedTextField();
        jbCancelar = new javax.swing.JButton();
        jsPesquisaCliente = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtClientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 920, 240));

        jbCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/salvar.png"))); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCadastrarMouseClicked(evt);
            }
        });
        getContentPane().add(jbCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, 140, 70));

        jbVisualizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/view.png"))); // NOI18N
        jbVisualizar.setText("Visualizar");
        jbVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbVisualizarMouseClicked(evt);
            }
        });
        getContentPane().add(jbVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 140, 70));

        jbRemover.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/remove2.png"))); // NOI18N
        jbRemover.setText("Remover");
        jbRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRemoverMouseClicked(evt);
            }
        });
        getContentPane().add(jbRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 140, 70));

        jbPesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/review.png"))); // NOI18N
        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPesquisarMouseClicked(evt);
            }
        });
        getContentPane().add(jbPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 140, 70));

        jlFiltros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlFiltros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlFiltros.setText("Filtros:");
        getContentPane().add(jlFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 50, 30));

        jcbPessoaFisica.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcbPessoaFisica.setText("Pessoa Física");
        jcbPessoaFisica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbPessoaFisicaMouseClicked(evt);
            }
        });
        getContentPane().add(jcbPessoaFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 130, 30));

        jcbPessoaJuridica.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcbPessoaJuridica.setText("Pessoa Júridica");
        jcbPessoaJuridica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbPessoaJuridicaMouseClicked(evt);
            }
        });
        getContentPane().add(jcbPessoaJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 140, 30));

        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtNomeKeyReleased(evt);
            }
        });
        getContentPane().add(jtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 690, 30));

        jlNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlNome.setText("Nome:");
        getContentPane().add(jlNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 60, 30));

        jlTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlTelefone.setText("Telefone:");
        getContentPane().add(jlTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, 30));

        jftTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftTelefoneKeyPressed(evt);
            }
        });
        getContentPane().add(jftTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 690, 30));

        jlCPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlCPF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlCPF.setText("CPF:");
        getContentPane().add(jlCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 60, 30));
        getContentPane().add(jftCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 690, 30));

        jbCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel.png"))); // NOI18N
        jbCancelar.setText("<html><center>Cancelar<br/></html>");
        jbCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbCancelarMousePressed(evt);
            }
        });
        getContentPane().add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, 140, 70));

        jsPesquisaCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa de Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N
        getContentPane().add(jsPesquisaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 940, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastrarMouseClicked
        if (jbCadastrar.isEnabled()) {
            cadastroCliente cliente = cadastroCliente.getInstancia();
            cliente.setLocationRelativeTo(this);
            cliente.setVisible(true);
        }

    }//GEN-LAST:event_jbCadastrarMouseClicked

    private void jbPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPesquisarMouseClicked
        // Verificação do pesquisar   // falta tudo !
//        if (!jtNome.getText().equals("") && validacao.validaLetras(jtNome.getText())) {
//            jtNome.setBackground(Color.white);
        popularTabelaQuery();
//        } else {
//            jtNome.setBackground(Color.red);
//        }
// arrumar a validacao...

//        if (jtTelefone.getText().equals("")) {
//            jtTelefone.setBackground(Color.white);
//        } else if (!jtTelefone.getText().equals("") && validaAlgo......) {
//            jtTelefone.setBackground(Color.white);
//        } else {
//            jtTelefone.setBackground(Color.red);
//            control = false;
//        }
        if (jcbPessoaFisica.isSelected()) {

        }
        if (jcbPessoaJuridica.isSelected()) {

        }


    }//GEN-LAST:event_jbPesquisarMouseClicked

    public void popularTabela() {
        if (jcbPessoaFisica.isSelected() && jcbPessoaJuridica.isSelected()) {
            jlCPF.setVisible(false);
            jlCPF.setEnabled(false);
            jftCPF.setVisible(false);
            jftCPF.setEnabled(false);

            PessoaDAO pessoaDAO = new PessoaDAO();
            List<Pessoa> pessoas = new ArrayList<Pessoa>();
            pessoas = pessoaDAO.getAll();
            jtClientes.setModel(new PessoaTableModel(pessoas));
        } else if (jcbPessoaFisica.isSelected()) {
            jlCPF.setVisible(true);
            jlCPF.setEnabled(true);
            jftCPF.setVisible(true);
            jftCPF.setEnabled(true);
            jlCPF.setText("CPF");
            mascaraCPF_CNPJ(true);
            PessoaFisicaDAO pessoaFisicaDAO = new PessoaFisicaDAO();
            List<PessoaFisica> pessoasFisicas = new ArrayList<PessoaFisica>();
            pessoasFisicas = pessoaFisicaDAO.getAll();
            jtClientes.setModel(new PessoaFisicaTableModel(pessoasFisicas));
        } else if (jcbPessoaJuridica.isSelected()) {
            jlCPF.setVisible(true);
            jlCPF.setEnabled(true);
            jftCPF.setVisible(true);
            jftCPF.setEnabled(true);
            jlCPF.setText("CNPJ");
            mascaraCPF_CNPJ(false);
            PessoaJuridicaDAO pessoaJuridicaDAO = new PessoaJuridicaDAO();
            List<PessoaJuridica> pessoasJuridicas = new ArrayList<PessoaJuridica>();
            pessoasJuridicas = pessoaJuridicaDAO.getAll();
            jtClientes.setModel(new PessoaJuridicaTableModel(pessoasJuridicas));
        } else {
            jlCPF.setVisible(false);
            jlCPF.setEnabled(false);
            jftCPF.setVisible(false);
            jftCPF.setEnabled(false);
            jtClientes.setModel(new PessoaTableModel());
        }

    }

    public void popularTabelaQuery() {
        if (!jtNome.getText().isEmpty()) {
            PessoaDAO pessoaDAO = new PessoaDAO();
            List<Pessoa> pessoas = new ArrayList<Pessoa>();
            pessoas = pessoaDAO.getQuery("WHERE nomePessoa LIKE '%" + jtNome.getText() + "%'");
            jtClientes.setModel(new PessoaTableModel(pessoas));
        } else if (!jftTelefone.getText().isEmpty() && jftTelefone.getText().trim().length() == 13) {
            PessoaDAO pessoaDAO = new PessoaDAO();
            List<Pessoa> pessoas = new ArrayList<Pessoa>();
            pessoas = pessoaDAO.getPorTelefone(jftTelefone.getText());
            jtClientes.setModel(new PessoaTableModel(pessoas));
        } else if (jcbPessoaJuridica.isSelected() && jftCPF.getText().trim().length() == 18) {
            PessoaJuridicaDAO pessoaJuridicaDAO = new PessoaJuridicaDAO();
            List<PessoaJuridica> pessoasJuridicas = new ArrayList<PessoaJuridica>();
            pessoasJuridicas = pessoaJuridicaDAO.getPorCNPJ(jftCPF.getText());
            jtClientes.setModel(new PessoaJuridicaTableModel(pessoasJuridicas));

        } else if (jcbPessoaFisica.isSelected() && jftCPF.getText().trim().length() == 14) {
            PessoaFisicaDAO pessoaFisicaDAO = new PessoaFisicaDAO();
            List<PessoaFisica> pessoasFisicas = new ArrayList<PessoaFisica>();
            pessoasFisicas = pessoaFisicaDAO.getPorCPF(jftCPF.getText());
            jtClientes.setModel(new PessoaFisicaTableModel(pessoasFisicas));
        }
    }

    public void mascaraTelefone() {
        try {
            jftTelefone.setFormatterFactory(new DefaultFormatterFactory(
                    new MaskFormatter("(##)####-####")));
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }

    public void mascaraCPF_CNPJ(boolean ativa) {
        try {
            if (ativa) {
                jftCPF.setFormatterFactory(new DefaultFormatterFactory(
                        new MaskFormatter("###.###.###-##")));
            } else {
                jftCPF.setFormatterFactory(new DefaultFormatterFactory(
                        new MaskFormatter("##.###.###/####-##")));
            }
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }

    private void jbVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVisualizarMouseClicked

        int linhaSelecionada = jtClientes.getSelectedRow();
        if (linhaSelecionada == -1) {
            return; //Nada selecionado
        }        
        if (jcbPessoaFisica.isSelected() && jcbPessoaJuridica.isSelected()) {
            
        } else if (jcbPessoaFisica.isSelected()) {
            PessoaFisicaTableModel pessoaFisicaModel = (PessoaFisicaTableModel) jtClientes.getModel();
            PessoaFisica pessoaFisicaSelecionada = pessoaFisicaModel.get(linhaSelecionada);
            PessoaFisicaDAO pessoaFisicaDAO = new PessoaFisicaDAO();
            cadastroCliente.getInstancia().pessoaFisica = pessoaFisicaSelecionada;
            setLocationRelativeTo(this);
            cadastroCliente.getInstancia().atualizarPessoaFisica(pessoaFisicaSelecionada);
            cadastroCliente.getInstancia().setVisible(true);
            cadastroCliente.getInstancia().DisableEnable(false);
            cadastroCliente.getInstancia().setLocationRelativeTo(this);
            cadastroCliente.getInstancia().setAlwaysOnTop(true);

        } else if (jcbPessoaJuridica.isSelected()) {
            PessoaJuridicaTableModel pessoaJuridicaModel = (PessoaJuridicaTableModel) jtClientes.getModel();
            PessoaJuridica pessoaJuridicaSelecionada = pessoaJuridicaModel.get(linhaSelecionada);
            PessoaFisicaDAO pessoaFisicaDAO = new PessoaFisicaDAO();
            cadastroCliente.getInstancia().pessoaJuridica = pessoaJuridicaSelecionada;
            setLocationRelativeTo(this);
            cadastroCliente.getInstancia().atualizarPessoaJuridica(pessoaJuridicaSelecionada);
            cadastroCliente.getInstancia().setVisible(true);
            cadastroCliente.getInstancia().DisableEnable(false);
            cadastroCliente.getInstancia().setLocationRelativeTo(this);
            cadastroCliente.getInstancia().setAlwaysOnTop(true);
        }


    }//GEN-LAST:event_jbVisualizarMouseClicked

    private void jbRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemoverMouseClicked
        if (jbRemover.isEnabled()) {
            int linhaSelecionada = jtClientes.getSelectedRow();
            if (linhaSelecionada == -1) {
                return; //Nada selecionado
            }
            if (jcbPessoaFisica.isSelected() && jcbPessoaJuridica.isSelected()) {
                PessoaTableModel pessoaModel = (PessoaTableModel) jtClientes.getModel();
                Pessoa pessoaSelecionada = pessoaModel.get(linhaSelecionada);
                PessoaDAO pessoaDAO = new PessoaDAO();
                pessoaDAO.removeById(pessoaSelecionada.getIdPessoa());
                pessoaModel.removeRow(linhaSelecionada);

            } else if (jcbPessoaFisica.isSelected()) {
                PessoaFisicaTableModel pessoaFisicaModel = (PessoaFisicaTableModel) jtClientes.getModel();
                PessoaFisica pessoaFisicaSelecionada = pessoaFisicaModel.get(linhaSelecionada);
                PessoaFisicaDAO pessoaFisicaDAO = new PessoaFisicaDAO();
                pessoaFisicaDAO.removeById(pessoaFisicaSelecionada.getIdPessoa());
                pessoaFisicaModel.removeRow(linhaSelecionada);

            } else if (jcbPessoaJuridica.isSelected()) {
                PessoaJuridicaTableModel pessoaJuridicaModel = (PessoaJuridicaTableModel) jtClientes.getModel();
                PessoaJuridica pessoaJuridicaSelecionada = pessoaJuridicaModel.get(linhaSelecionada);
                PessoaJuridicaDAO pessoaJuridicaDAO = new PessoaJuridicaDAO();
                pessoaJuridicaDAO.removeById(pessoaJuridicaSelecionada.getIdPessoa());
                pessoaJuridicaModel.removeRow(linhaSelecionada);
                System.out.println(pessoaJuridicaSelecionada.getCnpj());
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum campo foi selecionado!");
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jbRemoverMouseClicked

    private void jcbPessoaFisicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbPessoaFisicaMouseClicked
        popularTabela();
    }//GEN-LAST:event_jcbPessoaFisicaMouseClicked

    private void jcbPessoaJuridicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbPessoaJuridicaMouseClicked
        popularTabela();
    }//GEN-LAST:event_jcbPessoaJuridicaMouseClicked

    private void jftTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftTelefoneKeyPressed

        jlCPF.setVisible(false);
        jlCPF.setEnabled(false);
        jftCPF.setVisible(false);
        jftCPF.setEnabled(false);
    }//GEN-LAST:event_jftTelefoneKeyPressed

    private void jtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyReleased
        if (jtNome.getText().length() == 0) {
            jlCPF.setVisible(true);
            jlCPF.setEnabled(true);
            jftCPF.setVisible(true);
            jftCPF.setEnabled(true);
        } else {
            jlCPF.setVisible(false);
            jlCPF.setEnabled(false);
            jftCPF.setVisible(false);
            jftCPF.setEnabled(false);
        }
    }//GEN-LAST:event_jtNomeKeyReleased

    private void jbCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelarMousePressed
        if (jbCancelar.isEnabled()) {
            if (jbCancelar.isEnabled()) {
//            if (instancia == null) {
//                dispose();
//            } else {

                String ObjButtons[] = {"Sim", "Não"};
                int PromptResult = JOptionPane.showOptionDialog(this, "Esta certo que quer Fechar ?", "Verificação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, ObjButtons, ObjButtons[0]);
                if (PromptResult == JOptionPane.YES_OPTION) {
                    dispose();
                }
            }
        }
    }//GEN-LAST:event_jbCancelarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroClienteHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroClienteHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroClienteHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroClienteHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroClienteHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbRemover;
    private javax.swing.JButton jbVisualizar;
    private javax.swing.JCheckBox jcbPessoaFisica;
    private javax.swing.JCheckBox jcbPessoaJuridica;
    private javax.swing.JFormattedTextField jftCPF;
    private javax.swing.JFormattedTextField jftTelefone;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlFiltros;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JSeparator jsPesquisaCliente;
    private javax.swing.JTable jtClientes;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}
