/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CadFuncionario;

import Interface.TelaPrincipal.Sessao;

/**
 *
 * @author user
 */
public class ControleFuncionario extends javax.swing.JFrame {

    private static ControleFuncionario instancia;
    int user = Sessao.getInstance().getUsuario().getNivelAcesso();

    /**
     * Creates new form ControleFuncionario
     */
    public ControleFuncionario() {
        this.setUndecorated(true);
        initComponents();
    }
    
    public static ControleFuncionario getInstancia() {
        if (instancia == null) {
            instancia = new ControleFuncionario();
        }
        return instancia;
    }
    
    public static void encerrarInstancia(){
        instancia = null;
    }

    public void popular() {
        //Falta Cargo e departamento..

        jtfNome.setText("");
        jtfCodigoInterno.setText("");
        jftCPF.setText("");
        jtfRG.setText("");
    }

    public void DisableEnable(boolean b) {

        //falta nivel de acesso;
        jtUser.setEnabled(b);
        jtNovaSenha1.setEnabled(b);
        jtNovaSenha2.setEnabled(b);
    }

    public void verificaNivel() {
        if (user <= 2) {
            DisableEnable(false);
            jbEditar.setEnabled(true);
            jbConfirmar.setEnabled(false);

        } else {
            DisableEnable(false);
            jbConfirmar.setEnabled(false);
            jbEditar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCodigoInterno = new javax.swing.JLabel();
        jtfCodigoInterno = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlCPF = new javax.swing.JLabel();
        jftCPF = new javax.swing.JFormattedTextField();
        jlRG = new javax.swing.JLabel();
        jtfRG = new javax.swing.JTextField();
        jlNovaSenha = new javax.swing.JLabel();
        jlRepetirNovaSenha = new javax.swing.JLabel();
        jlNivelAcesso = new javax.swing.JLabel();
        jtNivelAcesso = new javax.swing.JTextField();
        jtUser = new javax.swing.JTextField();
        jtNovaSenha2 = new javax.swing.JTextField();
        jbConfirmar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jtCargo = new javax.swing.JTextField();
        jtDepartamento = new javax.swing.JTextField();
        jlCargo = new javax.swing.JLabel();
        jlDepartamento = new javax.swing.JLabel();
        jbEditar = new javax.swing.JButton();
        jtNovaSenha1 = new javax.swing.JTextField();
        jlNomeUsuario = new javax.swing.JLabel();
        jcbNivelAcesso = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 640));
        getContentPane().setLayout(null);

        jlCodigoInterno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlCodigoInterno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlCodigoInterno.setText("Código Interno:");
        getContentPane().add(jlCodigoInterno);
        jlCodigoInterno.setBounds(20, 20, 101, 30);

        jtfCodigoInterno.setEnabled(false);
        getContentPane().add(jtfCodigoInterno);
        jtfCodigoInterno.setBounds(130, 20, 70, 30);

        jlNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlNome.setText("Nome:");
        getContentPane().add(jlNome);
        jlNome.setBounds(310, 40, 50, 30);

        jtfNome.setEnabled(false);
        getContentPane().add(jtfNome);
        jtfNome.setBounds(370, 40, 580, 30);

        jlCPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlCPF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlCPF.setText("CPF:");
        getContentPane().add(jlCPF);
        jlCPF.setBounds(310, 80, 50, 30);

        jftCPF.setEnabled(false);
        getContentPane().add(jftCPF);
        jftCPF.setBounds(370, 80, 150, 30);

        jlRG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlRG.setText("RG:");
        getContentPane().add(jlRG);
        jlRG.setBounds(530, 80, 30, 30);

        jtfRG.setEnabled(false);
        getContentPane().add(jtfRG);
        jtfRG.setBounds(570, 80, 150, 30);

        jlNovaSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNovaSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlNovaSenha.setText("Nova Senha:");
        getContentPane().add(jlNovaSenha);
        jlNovaSenha.setBounds(270, 240, 90, 30);

        jlRepetirNovaSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlRepetirNovaSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlRepetirNovaSenha.setText("Repetir Nova Senha:");
        getContentPane().add(jlRepetirNovaSenha);
        jlRepetirNovaSenha.setBounds(220, 280, 140, 30);

        jlNivelAcesso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNivelAcesso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlNivelAcesso.setText("Nivel de Acesso:");
        getContentPane().add(jlNivelAcesso);
        jlNivelAcesso.setBounds(250, 160, 110, 30);
        getContentPane().add(jtNivelAcesso);
        jtNivelAcesso.setBounds(440, 160, 60, 30);
        getContentPane().add(jtUser);
        jtUser.setBounds(370, 200, 580, 30);
        getContentPane().add(jtNovaSenha2);
        jtNovaSenha2.setBounds(370, 280, 580, 30);

        jbConfirmar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/salvar.png"))); // NOI18N
        jbConfirmar.setText("Confirmar");
        getContentPane().add(jbConfirmar);
        jbConfirmar.setBounds(810, 320, 140, 70);

        jbCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        getContentPane().add(jbCancelar);
        jbCancelar.setBounds(510, 320, 140, 70);
        getContentPane().add(jtCargo);
        jtCargo.setBounds(790, 80, 160, 30);
        getContentPane().add(jtDepartamento);
        jtDepartamento.setBounds(370, 120, 150, 30);

        jlCargo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlCargo.setText("Cargo:");
        getContentPane().add(jlCargo);
        jlCargo.setBounds(730, 80, 50, 30);

        jlDepartamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlDepartamento.setText("Departamento:");
        getContentPane().add(jlDepartamento);
        jlDepartamento.setBounds(260, 120, 100, 30);

        jbEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editar2.png"))); // NOI18N
        jbEditar.setText("Editar");
        getContentPane().add(jbEditar);
        jbEditar.setBounds(660, 320, 140, 70);
        getContentPane().add(jtNovaSenha1);
        jtNovaSenha1.setBounds(370, 240, 580, 30);

        jlNomeUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNomeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlNomeUsuario.setText("Nome de Usuario:");
        getContentPane().add(jlNomeUsuario);
        jlNomeUsuario.setBounds(240, 200, 120, 30);

        jcbNivelAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbNivelAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNivelAcessoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbNivelAcesso);
        jcbNivelAcesso.setBounds(370, 160, 56, 30);

        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controle de Funcionário", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(210, 10, 760, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbNivelAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNivelAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNivelAcessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JComboBox<String> jcbNivelAcesso;
    private javax.swing.JFormattedTextField jftCPF;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlCodigoInterno;
    private javax.swing.JLabel jlDepartamento;
    private javax.swing.JLabel jlNivelAcesso;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeUsuario;
    private javax.swing.JLabel jlNovaSenha;
    private javax.swing.JLabel jlRG;
    private javax.swing.JLabel jlRepetirNovaSenha;
    private javax.swing.JTextField jtCargo;
    private javax.swing.JTextField jtDepartamento;
    private javax.swing.JTextField jtNivelAcesso;
    private javax.swing.JTextField jtNovaSenha1;
    private javax.swing.JTextField jtNovaSenha2;
    private javax.swing.JTextField jtUser;
    private javax.swing.JTextField jtfCodigoInterno;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfRG;
    // End of variables declaration//GEN-END:variables
}
