/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CadCargo;

/**
 *
 * @author a1502735
 */
public class cadastroCargo extends javax.swing.JFrame {

    /**
     * Creates new form cadastrarCargo
     */
    public cadastroCargo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfCodigoCargo = new javax.swing.JTextField();
        jlDescricaoCargo = new javax.swing.JLabel();
        jlNomeCargo = new javax.swing.JLabel();
        jlCodigoCargo = new javax.swing.JLabel();
        jlCodigoDepartamento = new javax.swing.JLabel();
        jtfCodigoDepartamento = new javax.swing.JTextField();
        jlNomeDepartamento = new javax.swing.JLabel();
        jtfNomeDepartamento = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jftTelefone = new javax.swing.JFormattedTextField();
        jlRamal = new javax.swing.JLabel();
        jtfRamal = new javax.swing.JTextField();
        jtNomeCargo = new javax.swing.JTextField();
        jbEditar = new javax.swing.JButton();
        jbCadastrarDepartamento = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescricaoCargo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jbCadastrarCargo1 = new javax.swing.JButton();
        jlCargosDepartamento = new javax.swing.JLabel();
        jbCancelarDepartamento = new javax.swing.JButton();
        jsCadastrarCargo = new javax.swing.JSeparator();
        jsCadastrarDepartamento = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(747, 640));
        getContentPane().setLayout(null);
        getContentPane().add(jtfCodigoCargo);
        jtfCodigoCargo.setBounds(360, 290, 200, 30);

        jlDescricaoCargo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlDescricaoCargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDescricaoCargo.setText("Descrição do Cargo");
        getContentPane().add(jlDescricaoCargo);
        jlDescricaoCargo.setBounds(230, 360, 330, 30);

        jlNomeCargo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNomeCargo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlNomeCargo.setText("Nome do Cargo:");
        getContentPane().add(jlNomeCargo);
        jlNomeCargo.setBounds(230, 330, 120, 30);

        jlCodigoCargo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlCodigoCargo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlCodigoCargo.setText("Código do Cargo:");
        getContentPane().add(jlCodigoCargo);
        jlCodigoCargo.setBounds(230, 290, 120, 30);

        jlCodigoDepartamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlCodigoDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlCodigoDepartamento.setText("Código do Departamento:");
        getContentPane().add(jlCodigoDepartamento);
        jlCodigoDepartamento.setBounds(30, 10, 170, 30);
        getContentPane().add(jtfCodigoDepartamento);
        jtfCodigoDepartamento.setBounds(210, 10, 80, 30);

        jlNomeDepartamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNomeDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlNomeDepartamento.setText("Nome do Departamento:");
        getContentPane().add(jlNomeDepartamento);
        jlNomeDepartamento.setBounds(30, 80, 160, 30);
        getContentPane().add(jtfNomeDepartamento);
        jtfNomeDepartamento.setBounds(200, 80, 360, 30);

        jlTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlTelefone.setText("Telefone:");
        getContentPane().add(jlTelefone);
        jlTelefone.setBounds(30, 120, 160, 30);
        getContentPane().add(jftTelefone);
        jftTelefone.setBounds(200, 120, 360, 30);

        jlRamal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlRamal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlRamal.setText("Ramal:");
        getContentPane().add(jlRamal);
        jlRamal.setBounds(30, 160, 160, 30);
        getContentPane().add(jtfRamal);
        jtfRamal.setBounds(200, 160, 360, 30);
        getContentPane().add(jtNomeCargo);
        jtNomeCargo.setBounds(360, 330, 200, 30);

        jbEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/salvar.png"))); // NOI18N
        jbEditar.setText("<html><center>Editar<br/>Cargo</html>");
        getContentPane().add(jbEditar);
        jbEditar.setBounds(570, 420, 140, 70);

        jbCadastrarDepartamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCadastrarDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/salvar.png"))); // NOI18N
        jbCadastrarDepartamento.setText("<html><center>Cadastrar<br/>Departamento</html>");
        jbCadastrarDepartamento.setIconTextGap(0);
        getContentPane().add(jbCadastrarDepartamento);
        jbCadastrarDepartamento.setBounds(570, 80, 140, 70);

        jbCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel.png"))); // NOI18N
        jbCancelar.setText("<html><center>Cancelar<br/></html>");
        getContentPane().add(jbCancelar);
        jbCancelar.setBounds(570, 500, 140, 70);

        jtaDescricaoCargo.setColumns(20);
        jtaDescricaoCargo.setRows(5);
        jScrollPane1.setViewportView(jtaDescricaoCargo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 390, 330, 180);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 310, 180, 260);

        jbCadastrarCargo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCadastrarCargo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/salvar.png"))); // NOI18N
        jbCadastrarCargo1.setText("<html><center>Cadastrar<br/>Cargo</html>");
        getContentPane().add(jbCadastrarCargo1);
        jbCadastrarCargo1.setBounds(570, 290, 140, 70);

        jlCargosDepartamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlCargosDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCargosDepartamento.setText("Cargos do Departamento");
        getContentPane().add(jlCargosDepartamento);
        jlCargosDepartamento.setBounds(30, 280, 180, 30);

        jbCancelarDepartamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCancelarDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel.png"))); // NOI18N
        jbCancelarDepartamento.setText("<html><center>Cancelar<br/></html>");
        getContentPane().add(jbCancelarDepartamento);
        jbCancelarDepartamento.setBounds(570, 160, 140, 70);

        jsCadastrarCargo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Cargo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N
        getContentPane().add(jsCadastrarCargo);
        jsCadastrarCargo.setBounds(10, 260, 720, 330);

        jsCadastrarDepartamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Departamento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N
        getContentPane().add(jsCadastrarDepartamento);
        jsCadastrarDepartamento.setBounds(10, 50, 720, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCadastrarCargo1;
    private javax.swing.JButton jbCadastrarDepartamento;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCancelarDepartamento;
    private javax.swing.JButton jbEditar;
    private javax.swing.JFormattedTextField jftTelefone;
    private javax.swing.JLabel jlCargosDepartamento;
    private javax.swing.JLabel jlCodigoCargo;
    private javax.swing.JLabel jlCodigoDepartamento;
    private javax.swing.JLabel jlDescricaoCargo;
    private javax.swing.JLabel jlNomeCargo;
    private javax.swing.JLabel jlNomeDepartamento;
    private javax.swing.JLabel jlRamal;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JSeparator jsCadastrarCargo;
    private javax.swing.JSeparator jsCadastrarDepartamento;
    private javax.swing.JTextField jtNomeCargo;
    private javax.swing.JTextArea jtaDescricaoCargo;
    private javax.swing.JTextField jtfCodigoCargo;
    private javax.swing.JTextField jtfCodigoDepartamento;
    private javax.swing.JTextField jtfNomeDepartamento;
    private javax.swing.JTextField jtfRamal;
    // End of variables declaration//GEN-END:variables
}
