/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CadCargo;

/**
 *
 * @author a1502735
 */
public class cadastroCargo extends javax.swing.JFrame {

    /**
     * Creates new form cadastrarCargo
     */
    public cadastroCargo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfCodigoCargo = new javax.swing.JTextField();
        jlDescricaoCargo = new javax.swing.JLabel();
        jlNomeCargo = new javax.swing.JLabel();
        jlCodigoCargo = new javax.swing.JLabel();
        jlCodigoDepartamento = new javax.swing.JLabel();
        jtfCodigoDepartamento = new javax.swing.JTextField();
        jlNomeDepartamento = new javax.swing.JLabel();
        jtfNomeDepartamento = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jftTelefone = new javax.swing.JFormattedTextField();
        jlRamal = new javax.swing.JLabel();
        jtfRamal = new javax.swing.JTextField();
        jtNomeCargo = new javax.swing.JTextField();
        jbEditar = new javax.swing.JButton();
        jbCadastrarDepartamento = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescricaoCargo = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jbCadastrarCargo1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(747, 640));
        getContentPane().setLayout(null);
        getContentPane().add(jtfCodigoCargo);
        jtfCodigoCargo.setBounds(180, 250, 100, 20);

        jlDescricaoCargo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlDescricaoCargo.setText("Descrição do Cargo");
        getContentPane().add(jlDescricaoCargo);
        jlDescricaoCargo.setBounds(180, 340, 200, 17);

        jlNomeCargo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNomeCargo.setText("Nome do Cargo");
        getContentPane().add(jlNomeCargo);
        jlNomeCargo.setBounds(180, 290, 110, 17);

        jlCodigoCargo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlCodigoCargo.setText("Código do Cargo");
        getContentPane().add(jlCodigoCargo);
        jlCodigoCargo.setBounds(180, 230, 150, 17);

        jlCodigoDepartamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlCodigoDepartamento.setText("Código do Departamento");
        getContentPane().add(jlCodigoDepartamento);
        jlCodigoDepartamento.setBounds(10, 20, 159, 17);
        getContentPane().add(jtfCodigoDepartamento);
        jtfCodigoDepartamento.setBounds(10, 40, 100, 20);

        jlNomeDepartamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNomeDepartamento.setText("Nome do Departamento");
        getContentPane().add(jlNomeDepartamento);
        jlNomeDepartamento.setBounds(130, 80, 160, 17);
        getContentPane().add(jtfNomeDepartamento);
        jtfNomeDepartamento.setBounds(130, 100, 250, 20);

        jlTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlTelefone.setText("Telefone");
        getContentPane().add(jlTelefone);
        jlTelefone.setBounds(130, 130, 100, 17);
        getContentPane().add(jftTelefone);
        jftTelefone.setBounds(130, 150, 110, 20);

        jlRamal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlRamal.setText("Ramal");
        getContentPane().add(jlRamal);
        jlRamal.setBounds(260, 130, 46, 17);
        getContentPane().add(jtfRamal);
        jtfRamal.setBounds(260, 150, 90, 20);
        getContentPane().add(jtNomeCargo);
        jtNomeCargo.setBounds(180, 310, 250, 20);

        jbEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/salvar.png"))); // NOI18N
        jbEditar.setText("<html><center>Editar<br/>Cargo</html>");
        getContentPane().add(jbEditar);
        jbEditar.setBounds(570, 340, 140, 70);

        jbCadastrarDepartamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCadastrarDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/salvar.png"))); // NOI18N
        jbCadastrarDepartamento.setText("<html><center>Cadastrar<br/>Departamento</html>");
        jbCadastrarDepartamento.setIconTextGap(0);
        getContentPane().add(jbCadastrarDepartamento);
        jbCadastrarDepartamento.setBounds(570, 90, 140, 70);

        jbCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel.png"))); // NOI18N
        jbCancelar.setText("<html><center>Cancelar<br/></html>");
        getContentPane().add(jbCancelar);
        jbCancelar.setBounds(570, 430, 140, 70);

        jtaDescricaoCargo.setColumns(20);
        jtaDescricaoCargo.setRows(5);
        jScrollPane1.setViewportView(jtaDescricaoCargo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 360, 360, 150);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(-10, 70, 760, 110);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 210, 770, 10);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 250, 140, 260);

        jbCadastrarCargo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCadastrarCargo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/salvar.png"))); // NOI18N
        jbCadastrarCargo1.setText("<html><center>Cadastrar<br/>Cargo</html>");
        getContentPane().add(jbCadastrarCargo1);
        jbCadastrarCargo1.setBounds(570, 250, 140, 70);

        jLabel1.setText("Cargos do Departamento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(14, 230, 140, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbCadastrarCargo1;
    private javax.swing.JButton jbCadastrarDepartamento;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JFormattedTextField jftTelefone;
    private javax.swing.JLabel jlCodigoCargo;
    private javax.swing.JLabel jlCodigoDepartamento;
    private javax.swing.JLabel jlDescricaoCargo;
    private javax.swing.JLabel jlNomeCargo;
    private javax.swing.JLabel jlNomeDepartamento;
    private javax.swing.JLabel jlRamal;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JTextField jtNomeCargo;
    private javax.swing.JTextArea jtaDescricaoCargo;
    private javax.swing.JTextField jtfCodigoCargo;
    private javax.swing.JTextField jtfCodigoDepartamento;
    private javax.swing.JTextField jtfNomeDepartamento;
    private javax.swing.JTextField jtfRamal;
    // End of variables declaration//GEN-END:variables
}
